### ISSUE TITLE
Web strange behavior / missing text 

### ISSUE THREAD

**Issue by rroblik** [fredlcore/bsb_lan#269] opened 2021-01-07 21:17 UTC
Hi @fredlcore,

I'm now connected successfully with my Atlantic Heater (RVS) 👍 

But I've some strange issues : 

1. The Web interface show my only "placeholder text" like that 
![image](https://user-images.githubusercontent.com/5805093/103945193-1dcca700-5135-11eb-90ff-139149e12e95.png)

2. I'm not able to set value using web even if in conf file I've `#define DEFAULT_FLAG 0` :
 `http://192.168.1.203/710`
![image](https://user-images.githubusercontent.com/5805093/103945380-6b491400-5135-11eb-85f9-3b9fde863d54.png)
`http://192.168.1.203/S710=21`
![image](https://user-images.githubusercontent.com/5805093/103945552-a51a1a80-5135-11eb-856b-0dfd97228da5.png)
 

Side notes : 
* I'm using [@dukess ajax alternative webserver](https://github.com/dukess/bsb_lan_ajax) configured as requested ; but the default webserver is displayed I think. My SD card have all required files.

Thanks

**Comment by dukess** [comment] 2021-01-07 21:27
The problem is that you can only use one language at a time.
Strings in "C" used as text resource identifiers for later substitute with real language.
By the way you can download latest ajax.html. It already support Web configuration.

**Comment by rroblik** [comment] 2021-01-07 21:32
Hu @dukess,

Ok yes; but ajax.html (renamed to index.html) is already here on the SD card

**Comment by dukess** [comment] 2021-01-07 21:34
If you get it from release i recommend to you download fresh version.

**Comment by dukess** [comment] 2021-01-07 21:37
Update: ...and latest language files from this project: when ajax.html can't find needed text string it display text ID.

**Comment by rroblik** [comment] 2021-01-07 21:40
I get it from your master branch ; is that ok ?

**Comment by dukess** [comment] 2021-01-07 21:59
Yes, sure

**Comment by fredlcore** [comment] 2021-01-08 11:09
Since this is a matter of @dukess' alternative webserver, I can't say anything about it, really, I'm sorry...
I would close this for now, but that should still make it possible for your two to continue the discussion if necessary.

**Closed by fredlcore** 2021-01-08 11:09 UTC

**Comment by rroblik** [comment] 2021-01-08 11:27
Yes no problem. Doing without it for now 👍
